services:
  nexo-app:
    image: ghcr.io/stratusti/steelelo:latest
    container_name: nextjs-app
    restart: unless-stopped
    ports:
      - "44385:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_APP_URL: https://elo.stratustelecom.com.br:44385
      JWT_SECRET: ${JWT_SECRET}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@10.10.100.46:5432/${POSTGRES_DB}
      REDIS_URL: redis://10.10.100.46:6379
    networks:
      - app-network

networks:
  app-network:
    external: true
    name: nexo-infra_app-network
