services:
  nextjs:
    image: ghcr.io/stratusti/steelelo:latest
    env_file: .env
    container_name: nextjs-app
    restart: unless-stopped
    ports:
      - "44385:3000"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    external: true
    name: nexo-infra_app-network
